# General Settings
app_name: "Malware Detector"
verison: "1.0.0"
log_file: "malware_detector.log"

# UI Settings
ui:
  enable: true # Set to false for CLI-only mode
  auto_refresh_interval: 5 #UI update frequency in seconds

#Scan Settings
scan:
  recursive: true # Scan subdirectories
  max_file_size: 50MB # Max file scan size (skips if greater)
  scan_zips: true # Scans ZIP and RAR files
  heuristic_analysis: true # Enable heurisitc_analysis

# Signature-Based Detection
signatures:
  enable: true
  malware_bazzar_db_url: "https://bazaar.abuse.ch/export/csv/full/"

# Heuristic Analysis
heuristic:
  enable: true
  entropy_threshold: 7.5
  suspicious_imports:
    - "LoadLibrary"
    - "VirtualAlloc"
    - "CreateRemoteThread"

# Background Execution Settings
background_execution:
  enable: true
  process_priority: "low"  # Options: low, normal, high
  auto_start: false  # Start on system boot?

# Logging Settings
logger:
  log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "malware_detector.log"
  log_format: "%(asctime)s - %(levelname)s - %(message)s"
  console_level: "INFO"


# System-Specific Settings
system:
  windows:
    scan_directory: "C:\\Users\\Public\\Documents"
  linux:
    scan_directory: "/home/user/Documents"
  macos:
    scan_directory: "/Users/user/Documents"