# General Settings
app_name: "Malware Detector"
verison: "1.0.0"
log_file: "malware_detector.log"

# UI Settings
ui:
  enable: true # Set to false for CLI-only mode
  color_theme : "dark-blue" #dark-blue, green, blue
  appearance_mode : "dark" #dark, light, system

#Scan Settings
scan:
  recursive: true # Scan subdirectories
  scan_zips: true # Scans ZIP and RAR files

# Signature-Based Detection
signatures:
  enable: true
  malware_bazzar_db_url: "https://bazaar.abuse.ch/export/csv/full/"
  local_db : "signatures.db"

# Logging Settings
logger:
  log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "malware_detector.log"
  log_format: "%(asctime)s - %(levelname)s - %(message)s"
  console_level: "INFO"